astronomer/terraform-google-astronomer-gcp

.gitignore, locals.tf, main.tf, variables.tf
**Issue**: https://github.com/astronomer/terraform-google-astronomer-gcp/issues/4
=> [#4] Get Latest available version for K8s Master & other Nodes

iam.tf
=> [#6] Fix Overriding Container Admin & Os Login User IAM Permissions

domain.tf, outputs.tf, variables.tf
This is the same fix from the AWS module.
=> Fix cert problem on houston

bastion.tf, domain.tf, main.tf, network.tf, node_pools.tf, outputs.tf, variables.tf
Also, don't create any of the bastion stuff when the management API is set to public
=> add configuration for gvisor to be only optionally enabled

iam.tf, outputs.tf, service-accounts.tf
closes https://github.com/astronomer/terraform-google-astronomer-gcp/issues/25
=> [#25] Separate Service Account for registry in separate deployments

buckets.tf, iam.tf, outputs.tf, service-accounts.tf
Issue: https://github.com/astronomer/issues/issues/360
This would be needed for https://github.com/astronomer/terraform-kubernetes-astronomer-system-components/pull/4
=> [astronomer/issues#360] Create Prerequisites for Velero

node_pools.tf, variables.tf
We will pass the values from Cloud Module
=> [astronomer/issues#379] Add taint on NodePool to restrict airflow pods to be a platform NodePool

iam.tf
https://cloud.drone.io/astronomer/terraform-google-astronomer-gcp/128/1/3
=> Avoid naming collision on google_project_iam_custom_role.velero_server

node_pools.tf, variables.tf
This pool will be used to direct all dynamic KubernetesExecutor and KubernetesPodOperator pods.
Issue: https://github.com/astronomer/issues/issues/545
=> [astronomer/issues#545] Add node pool for dynamic pods

node_pools.tf
=> Change the label for DynamicPod Node Pool

examples/from_scratch/main.tf, main.tf, variables.tf
Issue: https://github.com/astronomer/issues/issues/634
**Note**: I haven't tested it yet. Will do it soon
=> [astronomer/issues#634] Enable GKE Metered Usage 

firewalls.tf, variables.tf
This should enable KEDA and other api services
=> Make webhook ports generic

locals.tf, main.tf, network.tf, node_pools.tf, variables.tf
This work is primarily about switching to GKE channels, but involves some cleanup for future version compatibility and also the addition of a blue/green dynamic node pool.
=> Switch to GKE channels

node_pools.tf
Add lables to the nodes from each pool so we can see in k8s which nodes are in which node pools.
CI is failing on old TF formatting, so I fixed that too. (I was already planning to do this next)
=> Add labels and modernize

node_pools.tf
you can check out a plan showing no changes in production w/ this
https://app.circleci.com/pipelines/github/astronomer/google-environments/8415/workflows/aaa042e1-c260-41bc-89d7-9483f60d494b/jobs/13158/parallel-runs/0/steps/0-102﻿
=> commenting out labels for now

README.md, node_pools.tf, pipeline/run_terraform.sh, providers.tf.example, variables.tf
* google terraform provider version constraint added to use latest version, this addresses iam role issue which was observed in 2.20.0  gcp provider version
* node pool timeout changes has been fixed, this addresses resource  deletion timeout when "terraform destroy" command is executed
* changes in pipeline scripts and readme
=> terraform enhancements 

.circleci/config.yml, examples/from_scratch/main.tf, pipeline/run_terraform.sh
Related to astronomer/issues#2499
* enabling automated infra-creation for testing
=> circleci build enhancements

main.tf, variables.tf
k8s version 1.18.17-gke.700 has been removed by GKE team (in release channels)
=> update base k8s version

.circleci/config.yml, .pre-commit-config.yaml, variables.tf
Bump dev versions of pre-commit hooks and CI docker images
=> Bump dev versions

db.tf, examples/from_scratch/main.tf, variables.tf
currently postgres db values are hardcoded inside module , this change introduced to move from hardcoded value to variable type.
=> define postgres db as variable

locals.tf, outputs.tf
added cluster_name,ca_cert and endpoint to module output
=> added output extras to utilize with token auth

examples/from_scratch/main.tf, variables.tf
* updated gke default version
* added dev dns zone
* updates to email address
=> minor updates to gke terraform

terraform/main.tf, terraform/variables.tf
Add dataplane v2 support for GKE terraform config
=> add dataplane v2 support

.circleci/config.yml, terraform/variables.tf
update default gke supported version 1.27
=> update default gke supported version 1.27

terraform/buckets.tf, terraform/iam.tf, terraform/outputs.tf, terraform/variables.tf
issue link: https://github.com/astronomer/issues/issues/6485
=> allow velero bucket optionable

terraform/db.tf, terraform/locals.tf
https://github.com/astronomer/issues/issues/6535
=> add mysql database support
